# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1/

# получение списка курсов
GET {{baseUrl}}/courses/
Content-Type: application/json

###

# создание курса
POST {{baseUrl}}/course
Content-Type: application/jsons/

{
  "name": "Химия",
  "students": ""
}

###

# обновление датчика
PATCH {{baseUrl}}/courses/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json