# Примеры API-запросов
@baseUrl = http://localhost:8000/api/v1

###

# Получение списка курсов
GET {{baseUrl}}/courses/
Content-Type: application/json

###

# Создание курса
POST {{baseUrl}}/courses/
Content-Type: application/json

{
  "name": "Химия",
  "students": []
}

###

# Фильтрация курсов по имени
GET {{baseUrl}}/courses/?name=Химия
Content-Type: application/json

###

# Фильтрация курсов по id
GET {{baseUrl}}/courses/?id=1
Content-Type: application/json


###

# Обновление курса
PUT {{baseUrl}}/courses/1/
Content-Type: application/json

{
  "name": "Обновлённая Химия",
  "students": []
}

###

# Удаление курса
DELETE {{baseUrl}}/courses/1/
Content-Type: application/json